### ISSUE TITLE
Using WKWebView on iOS 8 and newer

### ISSUE THREAD

**Issue by ncarandini** [MicrosoftDocs/xamarin-docs.it-it#5]
As reported by David Ortinau on his [blog post](https://blog.xamarin.com/xamarin-forms-3-3-0-little-things-huge-difference/), Xamarin Forms 3.3.0 has added the availability of WKWebView without the need of a custom control.
Simply add this directive to your AssemblyInfo.cs:
`[assembly: ExportRenderer(typeof(WebView), typeof(WKWebViewRenderer))]`

I think this should be added to the document, to correct and extend the sentence:
"If that's a problem, you'll need to write a custom renderer that uses WKWebView, which supports faster browsing" in the Performance section.

Note that this is only for the English version of the Italian page, that is oddly NOT the same version of the English page!

Compare the [English page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview) to the [Italian page](https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/webview?tabs=vswin), after switching to the English version

![image](https://user-images.githubusercontent.com/139274/47962698-e3c95d00-e020-11e8-83bb-4a89b4656d0d.png)

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [WebView di xamarin. Forms - Xamarin](https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/webview?tabs=vswin)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs.it-IT/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #991](https://github.com/MicrosoftDocs/xamarin-docs/issues/991) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ncarandini 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/991.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
