### ISSUE TITLE
MainActivity.Instance problem

### ISSUE THREAD

**Issue by SoftArea-srl** [MicrosoftDocs/xamarin-docs.it-it#6]
in iOS works perfectly, but in Android, within the DependencyServiceSample.Droid I am getting a compile error telling me that "Instance" is not existing in "MainActivity". I have then added the following instruction in MainActivity: 
    internal static MainActivity Instance { get; private set; }
but I am getting a runtime error 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Selezione di una foto dalla Raccolta immagini - Xamarin](https://docs.microsoft.com/it-it/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs.it-IT/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hello, @SoftArea-srl 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
